name: GitHub Actions Demo

on: 
  push:
    branches: [ main ]
    paths-ignore: [.github/**]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Output names
        run: |
          echo "triggered: ${{ github.event_name }}"
          echo "branch: ${{ github.ref }}"
      - uses: actions/checkout@v3.3.0
      - name: List all files in the repository
        run: |
          echo "files in the repos:"
          tree
