name: Hello World Docker
on:
  push:
    branches: [ main ] # The workflow should run on every push if the action has changed.
  workflow_dispatch: # Also add a manual trigger to start the build manually.

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository to reference the action locally and without a git reference.
      - uses: actions/checkout@v3.3.0

      - name: Run container
        uses: ./hello-world-docker-action
        id: helloworld

      - run: |
          echo "output: ${{ steps.helloworld.outputs.time }}"
